# Generated by Django 3.2.9 on 2021-12-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardprogramregisterhistory',
            name='new_active_status',
        ),
        migrations.RemoveField(
            model_name='rewardprogramregisterhistory',
            name='old_active_status',
        ),
        migrations.AlterField(
            model_name='rewardprogramregisterhistory',
            name='reward_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.rewardprogram'),
        ),
    ]
